language: python

env:
  matrix:
    - TOXENV=py36

before_install:
  # work around https://github.com/travis-ci/travis-ci/issues/8363
  - pyenv global system 3.6

install:
  - pip install tox

script:
  - tox
