version: "{build}"

build: false

environment:
    global:
        SOURCE_DIRS: bead bead_cli tests
    matrix:
        - PYTHON: "C:/Python36"
          CHECK_SOURCE_CODE: TRUE
          DUMP_CI_VM_INFO: TRUE

        - PYTHON: "C:/Python36"
          RUN_TESTS: TRUE

install:
    - "set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - if defined CHECK_SOURCE_CODE pip install flake8
    - if defined RUN_TESTS         pip install -r requirements.txt -r test_requirements.txt

test_script:
    - "if defined DUMP_CI_VM_INFO dir C:\\Python*"
    - if defined DUMP_CI_VM_INFO   set
    - if defined RUN_TESTS         pip freeze
    - if defined RUN_TESTS         pytest --cov=. --cov-report=term-missing
    - if defined CHECK_SOURCE_CODE flake8 %SOURCE_DIRS%

platform:
    - AnyCPU
