name: Tests

on:
  push:
    branches: [ main, next ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Pin Python version
      run: uv python pin ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --dev

    - name: Run CLI tests
      run: uv run python -W ignore::ResourceWarning -m pytest bead_cli/ -v

    - name: Run core tests
      run: uv run python -W ignore::ResourceWarning -m pytest bead/ -v

    - name: Run additional tests
      run: uv run python -W ignore::ResourceWarning -m pytest tests/ -v
